"use client";

import Link from "next/link";
import {useParams} from "next/navigation";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {MythoriaAlert} from "@/components/ui/MythoriaAlert";
import {MythoriaBadge} from "@/components/ui/MythoriaBadge";
import {MythoriaEmptyState} from "@/components/ui/MythoriaEmptyState";
import {MythoriaPageHeader} from "@/components/ui/MythoriaPageHeader";
import {MythoriaSpinner} from "@/components/ui/MythoriaSpinner";

type Character={id:string;name:string;level:number;gold:number;charisma:number};
type Merchant={id:string;name:string;description:string;price_modifier:number;faction_id:string|null;icon:string};
type MerchantItem={id:string;merchant_id:string;name:string;description:string;item_type:string;rarity:string;price:number;stock:number|null;attack_bonus:number;defense_bonus:number;magic_bonus:number;health_bonus:number;mana_bonus:number};
type InventoryItem={id:string;name:string;item_type:string;rarity:string;quantity:number;is_equipped:boolean;value:number};
type Recipe={id:string;name:string;description:string;required_level:number;gold_cost:number;result_name:string;result_rarity:string;result_attack_bonus:number;result_defense_bonus:number;result_magic_bonus:number;result_health_bonus:number;result_mana_bonus:number;icon:string};
type Ingredient={recipe_id:string;item_name:string;quantity:number};
type Transaction={id:number;kind:"buy"|"sell"|"craft";item_name:string;quantity:number;gold_change:number;created_at:string};

export default function MarketPage(){
 const{id}=useParams<{id:string}>();const supabase=useMemo(()=>createClient(),[]);
 const[character,setCharacter]=useState<Character|null>(null);const[merchants,setMerchants]=useState<Merchant[]>([]);const[wares,setWares]=useState<MerchantItem[]>([]);const[inventory,setInventory]=useState<InventoryItem[]>([]);const[recipes,setRecipes]=useState<Recipe[]>([]);const[ingredients,setIngredients]=useState<Ingredient[]>([]);const[transactions,setTransactions]=useState<Transaction[]>([]);
 const[reputation,setReputation]=useState<Map<string,number>>(new Map());
 const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[message,setMessage]=useState("");

 const load=useCallback(async()=>{setLoading(true);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Du bist nicht angemeldet.");setLoading(false);return;}
  const{data:c,error:ce}=await supabase.from("characters").select("id,name,level,gold,charisma").eq("id",id).eq("user_id",user.id).maybeSingle().overrideTypes<Character|null,{merge:false}>();if(ce||!c){setError(ce?.message??"Charakter nicht gefunden.");setLoading(false);return;}setCharacter(c);
  const[mr,wr,ir,rr,gr,tr,pr]=await Promise.all([
   supabase.from("merchants").select("id,name,description,price_modifier,faction_id,icon").order("name").overrideTypes<Merchant[],{merge:false}>(),
   supabase.from("merchant_items").select("id,merchant_id,name,description,item_type,rarity,price,stock,attack_bonus,defense_bonus,magic_bonus,health_bonus,mana_bonus").order("sort_order").overrideTypes<MerchantItem[],{merge:false}>(),
   supabase.from("inventory_items").select("id,name,item_type,rarity,quantity,is_equipped,value").eq("character_id",id).eq("user_id",user.id).order("name").overrideTypes<InventoryItem[],{merge:false}>(),
   supabase.from("crafting_recipes").select("id,name,description,required_level,gold_cost,result_name,result_rarity,result_attack_bonus,result_defense_bonus,result_magic_bonus,result_health_bonus,result_mana_bonus,icon").order("sort_order").overrideTypes<Recipe[],{merge:false}>(),
   supabase.from("recipe_ingredients").select("recipe_id,item_name,quantity").overrideTypes<Ingredient[],{merge:false}>(),
   supabase.from("economy_transactions").select("id,kind,item_name,quantity,gold_change,created_at").eq("character_id",id).eq("user_id",user.id).order("created_at",{ascending:false}).limit(12).overrideTypes<Transaction[],{merge:false}>(),
   supabase.from("character_reputation").select("faction_id,reputation").eq("character_id",id).eq("user_id",user.id).overrideTypes<Array<{faction_id:string;reputation:number}>,{merge:false}>(),
  ]);
  const firstError=mr.error??wr.error??ir.error??rr.error??gr.error??tr.error??pr.error;if(firstError)setError(firstError.message);else{setMerchants(mr.data??[]);setWares(wr.data??[]);setInventory(ir.data??[]);setRecipes(rr.data??[]);setIngredients(gr.data??[]);setTransactions(tr.data??[]);setReputation(new Map((pr.data??[]).map(entry=>[entry.faction_id,entry.reputation])));}setLoading(false);
 },[id,supabase]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function run(kind:"buy"|"sell"|"craft",targetId:string,label:string){setBusy(targetId);setError("");setMessage("");const result=kind==="buy"?await supabase.rpc("buy_merchant_item",{p_character_id:id,p_merchant_item_id:targetId,p_quantity:1}):kind==="sell"?await supabase.rpc("sell_inventory_item",{p_character_id:id,p_item_id:targetId,p_quantity:1}):await supabase.rpc("craft_character_item",{p_character_id:id,p_recipe_id:targetId});if(result.error)setError(economyError(result.error.message));else{setMessage(kind==="buy"?`${label} wurde gekauft.`:kind==="sell"?`${label} wurde verkauft.`:`${label} wurde hergestellt.`);await load();}setBusy("");}
 if(loading)return <main className="mythoria-page flex min-h-screen items-center justify-center"><MythoriaSpinner size="large"/></main>;if(!character)return <main className="mythoria-page mx-auto max-w-4xl px-4 py-10"><MythoriaAlert variant="error">{error||"Charakter nicht gefunden."}</MythoriaAlert></main>;
 const discount=Math.min(.15,Math.max(0,(character.charisma-10)*.01));const owned=new Map<string,number>();for(const item of inventory)owned.set(item.name,(owned.get(item.name)??0)+item.quantity);
 return <main className="mythoria-page mx-auto max-w-[1440px] px-4 py-8 sm:px-6"><MythoriaPageHeader eyebrow="HANDEL & HANDWERK" title={`Marktplatz für ${character.name}`} description="Kaufe Ausrüstung, verkaufe Beute und verwandle Materialien in neue Gegenstände." actions={<div className="flex flex-wrap gap-3"><MythoriaBadge variant="gold">{character.gold.toLocaleString("de-DE")} Gold</MythoriaBadge><Link href={`/dashboard/characters/${id}`} className="mythoria-button-secondary">Zum Charakter</Link></div>}/>
 {error&&<MythoriaAlert variant="error" className="mt-6">{error}</MythoriaAlert>}{message&&<MythoriaAlert variant="success" className="mt-6">{message}</MythoriaAlert>}
 <section className="mt-8">{merchants.map(merchant=>{const factionReputation=merchant.faction_id?reputation.get(merchant.faction_id)??0:0;const reputationDiscount=Math.min(.10,Math.max(0,factionReputation)/5000);return <div key={merchant.id}><div className="mythoria-panel flex items-start gap-4 p-5"><span aria-hidden="true" className="text-4xl">{merchant.icon}</span><div><h2 className="mythoria-subheading text-2xl">{merchant.name}</h2><p className="mt-2 text-sm text-[var(--mythoria-text-muted)]">{merchant.description}</p><p className="mt-2 text-xs text-[var(--mythoria-gold-light)]">Charisma-Rabatt: {Math.round(discount*100)} % · Rufrabatt: {(reputationDiscount*100).toFixed(1)} %</p></div></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{wares.filter(item=>item.merchant_id===merchant.id).map(item=>{const price=Math.ceil(item.price*merchant.price_modifier*(1-discount-reputationDiscount));return <article key={item.id} className="mythoria-card p-5"><div className="flex items-center justify-between gap-3"><h3 className="mythoria-subheading text-xl">{item.name}</h3><MythoriaBadge variant="gold">{price} Gold</MythoriaBadge></div><p className="mt-2 text-xs text-[var(--mythoria-text-muted)]">{item.rarity} · Bestand {item.stock??"∞"}</p><p className="mt-3 min-h-12 text-sm leading-6 text-[var(--mythoria-text-secondary)]">{item.description}</p><BonusLine item={item}/><button disabled={busy!==""||item.stock===0||character.gold<price} onClick={()=>void run("buy",item.id,item.name)} className="mythoria-button-primary mt-5 w-full">Kaufen</button></article>})}</div></div>})}</section>
 <section className="mt-12 border-t border-[var(--mythoria-border)] pt-10"><h2 className="mythoria-heading text-2xl">Beute verkaufen</h2><p className="mt-2 text-sm text-[var(--mythoria-text-muted)]">Der Händler zahlt ungefähr die Hälfte des Wertes. Charisma verbessert den Erlös.</p>{inventory.filter(item=>!item.is_equipped).length===0?<MythoriaEmptyState className="mt-5" title="Nichts zu verkaufen" description="Ausgerüstete Gegenstände werden zum Schutz nicht angeboten."/>:<div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{inventory.filter(item=>!item.is_equipped).map(item=>{const price=Math.max(1,Math.floor(Math.max(item.value,1)*.5*(1+discount)));return <article key={item.id} className="mythoria-card flex items-center justify-between gap-4 p-4"><div><h3 className="font-bold">{item.name}</h3><p className="mt-1 text-xs text-[var(--mythoria-text-muted)]">Menge {item.quantity} · {price} Gold pro Stück</p></div><button disabled={busy!==""} onClick={()=>void run("sell",item.id,item.name)} className="mythoria-button-secondary">1 verkaufen</button></article>})}</div>}</section>
 <section className="mt-12 border-t border-[var(--mythoria-border)] pt-10"><h2 className="mythoria-heading text-2xl">Werkstatt</h2><p className="mt-2 text-sm text-[var(--mythoria-text-muted)]">Rezepte verbrauchen Materialien und eine kleine Handwerksgebühr.</p><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{recipes.map(recipe=>{const needs=ingredients.filter(entry=>entry.recipe_id===recipe.id);const hasMaterials=needs.every(entry=>(owned.get(entry.item_name)??0)>=entry.quantity);const available=hasMaterials&&character.level>=recipe.required_level&&character.gold>=recipe.gold_cost;return <article key={recipe.id} className="mythoria-card p-5"><span aria-hidden="true" className="text-3xl">{recipe.icon}</span><div className="mt-3 flex items-center justify-between gap-3"><h3 className="mythoria-subheading text-xl">{recipe.name}</h3><MythoriaBadge variant="gold">{recipe.gold_cost} Gold</MythoriaBadge></div><p className="mt-3 min-h-12 text-sm text-[var(--mythoria-text-muted)]">{recipe.description}</p><ul className="mt-4 space-y-1 text-xs text-[var(--mythoria-text-secondary)]">{needs.map(entry=><li key={entry.item_name} className={(owned.get(entry.item_name)??0)>=entry.quantity?"text-[var(--mythoria-success)]":"text-red-300"}>{entry.item_name}: {owned.get(entry.item_name)??0}/{entry.quantity}</li>)}</ul><button disabled={busy!==""||!available} onClick={()=>void run("craft",recipe.id,recipe.result_name)} className="mythoria-button-primary mt-5 w-full">{character.level<recipe.required_level?`Ab Stufe ${recipe.required_level}`:!hasMaterials?"Zutaten fehlen":"Herstellen"}</button></article>})}</div></section>
 <section className="mt-12 border-t border-[var(--mythoria-border)] pt-10"><h2 className="mythoria-heading text-2xl">Letzte Transaktionen</h2>{transactions.length===0?<p className="mt-4 text-sm text-[var(--mythoria-text-muted)]">Noch keine Handelsbewegungen.</p>:<div className="mythoria-panel mt-5 divide-y divide-[var(--mythoria-border)]">{transactions.map(tx=><div key={tx.id} className="flex items-center justify-between gap-4 p-4 text-sm"><div><p className="font-bold">{tx.item_name} × {tx.quantity}</p><p className="text-xs text-[var(--mythoria-text-muted)]">{{buy:"Kauf",sell:"Verkauf",craft:"Herstellung"}[tx.kind]} · {new Date(tx.created_at).toLocaleString("de-DE")}</p></div><strong className={tx.gold_change>=0?"text-[var(--mythoria-success)]":"text-[var(--mythoria-gold-light)]"}>{tx.gold_change>0?"+":""}{tx.gold_change} Gold</strong></div>)}</div>}</section>
 </main>;
}
function BonusLine({item}:{item:MerchantItem}){const values=[["ANG",item.attack_bonus],["VER",item.defense_bonus],["MAG",item.magic_bonus],["LP",item.health_bonus],["MP",item.mana_bonus]].filter(([,value])=>Number(value)>0);return values.length?<div className="mt-3 flex flex-wrap gap-2 text-xs">{values.map(([label,value])=><span key={String(label)} className="rounded-lg bg-black/25 px-2 py-1">+{value} {label}</span>)}</div>:null}
function economyError(message:string){if(message.includes("not enough gold"))return"Dafür ist nicht genug Gold vorhanden.";if(message.includes("not enough stock"))return"Der Händler hat nicht genügend Exemplare auf Lager.";if(message.includes("unavailable for sale"))return"Ausgerüstete oder nicht verfügbare Gegenstände können nicht verkauft werden.";if(message.includes("missing ingredient"))return"Mindestens eine benötigte Zutat fehlt.";if(message.includes("level too low"))return"Die benötigte Charakterstufe wurde noch nicht erreicht.";return message}
