"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {MythoriaLogo} from "@/components/branding/MythoriaLogo";
import {DashboardTopbar} from "./DashboardTopbar";
import {UserMenu} from "./UserMenu";
import {dashboardNavigation,isNavigationItemActive} from "./navigation";
export function MobileNavigation({email,displayName}:{email:string;displayName?:string}){const[open,setOpen]=useState(false);const pathname=usePathname();const closeRef=useRef<HTMLButtonElement>(null);useEffect(()=>{if(!open)return;closeRef.current?.focus();const previousOverflow=document.body.style.overflow;document.body.style.overflow="hidden";function key(event:KeyboardEvent){if(event.key==="Escape")setOpen(false)}document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=previousOverflow}},[open]);return <><DashboardTopbar onMenuOpen={()=>setOpen(true)}/>{open&&<div className="fixed inset-0 z-[80] lg:hidden"><button type="button" aria-label="Navigation schließen" onClick={()=>setOpen(false)} className="absolute inset-0 bg-black/75"/><aside role="dialog" aria-modal="true" aria-label="Mobile Navigation" className="absolute inset-y-0 left-0 flex w-[min(88vw,330px)] flex-col border-r border-[var(--mythoria-border-gold)] bg-[var(--mythoria-background)] shadow-2xl"><div className="flex items-center justify-between border-b border-[var(--mythoria-border)] p-3"><MythoriaLogo size="small"/><button ref={closeRef} type="button" onClick={()=>setOpen(false)} aria-label="Menü schließen" className="mythoria-focus-ring min-h-11 min-w-11 rounded-xl border border-[var(--mythoria-border)] text-xl">×</button></div><nav aria-label="Mobile Hauptnavigation" className="flex-1 space-y-1 overflow-y-auto p-3">{dashboardNavigation.map(item=>{const active=isNavigationItemActive(pathname,item);if(!item.href)return <div key={item.label} aria-disabled="true" className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm text-[var(--mythoria-text-disabled)]"><span aria-hidden="true" className="w-6 text-center">{item.icon}</span>{item.label}<span className="ml-auto text-xs">Bald</span></div>;return <Link key={item.label} href={item.href} onClick={()=>setOpen(false)} aria-current={active?"page":undefined} className={["flex min-h-11 items-center gap-3 rounded-xl border px-3 text-sm font-semibold",active?"border-[var(--mythoria-border-gold)] bg-[var(--mythoria-green-dark)]/45 text-[var(--mythoria-neon-soft)]":"border-transparent text-[var(--mythoria-text-secondary)]"].join(" ")}><span aria-hidden="true" className="w-6 text-center">{item.icon}</span>{item.label}</Link>})}</nav><UserMenu compact email={email} displayName={displayName}/></aside></div>}</>}
