"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {MythoriaAlert} from "@/components/ui/MythoriaAlert";
import {MythoriaBadge} from "@/components/ui/MythoriaBadge";
import {MythoriaEmptyState} from "@/components/ui/MythoriaEmptyState";
import {MythoriaPageHeader} from "@/components/ui/MythoriaPageHeader";
import {MythoriaSpinner} from "@/components/ui/MythoriaSpinner";
type Notification={id:string;notification_type:"friend"|"party"|"guild"|"achievement"|"system";title:string;message:string;link:string|null;read_at:string|null;created_at:string};
const typeLabels={friend:"Freundschaft",party:"Gruppe",guild:"Gilde",achievement:"Erfolg",system:"System"};const icons={friend:"♧",party:"♙",guild:"♜",achievement:"★",system:"◇"};
export default function NotificationsPage(){const supabase=useMemo(()=>createClient(),[]);const router=useRouter();const[items,setItems]=useState<Notification[]>([]);const[filter,setFilter]=useState<"all"|"unread">("all");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Du bist nicht angemeldet.");setLoading(false);return;}const{data,error:loadError}=await supabase.from("notifications").select("id,notification_type,title,message,link,read_at,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100).overrideTypes<Notification[],{merge:false}>();if(loadError)setError(loadError.message);else setItems(data??[]);setLoading(false)},[supabase]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function mark(item:Notification,navigate=false){setBusy(item.id);setError("");if(!item.read_at){const{error:rpcError}=await supabase.rpc("mark_notification_read",{p_notification_id:item.id});if(rpcError){setError(rpcError.message);setBusy("");return;}}setItems(current=>current.map(entry=>entry.id===item.id?{...entry,read_at:entry.read_at??new Date().toISOString()}:entry));setBusy("");if(navigate&&item.link)router.push(item.link);}
 async function markAll(){setBusy("all");const{error:rpcError}=await supabase.rpc("mark_all_notifications_read");if(rpcError)setError(rpcError.message);else setItems(current=>current.map(item=>({...item,read_at:item.read_at??new Date().toISOString()})));setBusy("");}
 async function remove(id:string){setBusy(id);const{error:rpcError}=await supabase.rpc("delete_notification",{p_notification_id:id});if(rpcError)setError(rpcError.message);else setItems(current=>current.filter(item=>item.id!==id));setBusy("");}
 if(loading)return <main className="mythoria-page flex min-h-screen items-center justify-center"><MythoriaSpinner size="large"/></main>;const unread=items.filter(item=>!item.read_at).length;const visible=filter==="unread"?items.filter(item=>!item.read_at):items;
 return <main className="mythoria-page mx-auto max-w-5xl px-4 py-8 sm:px-6"><MythoriaPageHeader eyebrow="CHRONIK-MELDUNGEN" title="Benachrichtigungen" description="Freundschaften, Gruppen, Gilden und Erfolge an einem Ort." actions={unread>0?<button disabled={busy!==""} onClick={()=>void markAll()} className="mythoria-button-secondary">Alle als gelesen markieren</button>:undefined}/>{error&&<MythoriaAlert variant="error" className="mt-6">{error}</MythoriaAlert>}
 <div className="mt-7 flex flex-wrap items-center gap-3"><button onClick={()=>setFilter("all")} className={filter==="all"?"mythoria-button-primary":"mythoria-button-secondary"}>Alle · {items.length}</button><button onClick={()=>setFilter("unread")} className={filter==="unread"?"mythoria-button-primary":"mythoria-button-secondary"}>Ungelesen · {unread}</button></div>
 {visible.length===0?<MythoriaEmptyState className="mt-6" icon="◇" title={filter==="unread"?"Alles gelesen":"Noch keine Meldungen"} description={filter==="unread"?"Du hast keine ungelesenen Benachrichtigungen.":"Neue soziale Ereignisse und Erfolge erscheinen künftig hier."}/>:<section className="mt-6 space-y-3">{visible.map(item=><article key={item.id} className={`mythoria-card flex flex-col gap-4 p-5 sm:flex-row sm:items-start ${item.read_at?"opacity-70":"border-[var(--mythoria-border-gold)]"}`}><span aria-hidden="true" className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border border-[var(--mythoria-border)] bg-black/20 text-2xl">{icons[item.notification_type]}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-[var(--mythoria-text)]">{item.title}</h2>{!item.read_at&&<MythoriaBadge variant="gold">Neu</MythoriaBadge>}<MythoriaBadge>{typeLabels[item.notification_type]}</MythoriaBadge></div><p className="mt-2 text-sm leading-6 text-[var(--mythoria-text-muted)]">{item.message}</p><p className="mt-2 text-xs text-[var(--mythoria-text-disabled)]">{new Date(item.created_at).toLocaleString("de-DE")}</p></div><div className="flex shrink-0 flex-wrap gap-2">{item.link&&<button disabled={busy!==""} onClick={()=>void mark(item,true)} className="mythoria-button-primary">Öffnen</button>}{!item.read_at&&<button disabled={busy!==""} onClick={()=>void mark(item)} className="mythoria-button-secondary">Gelesen</button>}<button disabled={busy!==""} onClick={()=>void remove(item.id)} aria-label={`${item.title} löschen`} className="mythoria-button-secondary">×</button></div></article>)}</section>}</main>}
