"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {MythoriaAlert} from "@/components/ui/MythoriaAlert";
import {MythoriaBadge} from "@/components/ui/MythoriaBadge";
import {MythoriaPageHeader} from "@/components/ui/MythoriaPageHeader";
import {MythoriaSpinner} from "@/components/ui/MythoriaSpinner";
type Overview={users:number;characters:number;activeAdventures:number;activeCombats:number;guilds:number;friendships:number;notifications:number;suspendedUsers:number;role:"super_admin"|"content_admin"|"moderator"};type Content={id:string;name:string;status:string;type:string};type Profile={id:string;display_name:string};type Moderation={user_id:string;status:string;reason:string|null};type Audit={id:number;admin_id:string;action:string;target_type:string;target_id:string|null;details:Record<string,unknown>;created_at:string};
export default function AdminPage(){const supabase=useMemo(()=>createClient(),[]);const[overview,setOverview]=useState<Overview|null>(null);const[content,setContent]=useState<Content[]>([]);const[profiles,setProfiles]=useState<Profile[]>([]);const[moderation,setModeration]=useState<Moderation[]>([]);const[audit,setAudit]=useState<Audit[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const{data:overviewData,error:overviewError}=await supabase.rpc("get_admin_overview");if(overviewError){setOverview(null);setError(adminError(overviewError.message));setLoading(false);return;}setOverview(overviewData as Overview);const[qr,er,mr,rr,fr,cr,pr,ur,ar]=await Promise.all([supabase.from("quests").select("id,title,status").order("title"),supabase.from("enemies").select("id,name,status").order("name"),supabase.from("merchants").select("id,name,status").order("name"),supabase.from("crafting_recipes").select("id,name,status").order("name"),supabase.from("factions").select("id,name,status").order("name"),supabase.from("companion_templates").select("id,name,status").order("name"),supabase.from("public_profiles").select("id,display_name").order("display_name").overrideTypes<Profile[],{merge:false}>(),supabase.from("user_moderation").select("user_id,status,reason").overrideTypes<Moderation[],{merge:false}>(),supabase.from("admin_audit_log").select("id,admin_id,action,target_type,target_id,details,created_at").order("created_at",{ascending:false}).limit(30).overrideTypes<Audit[],{merge:false}>()]);const first=qr.error??er.error??mr.error??rr.error??fr.error??cr.error??pr.error??ur.error??ar.error;if(first)setError(first.message);else{setContent([...(qr.data??[]).map(row=>({id:String(row.id),name:String(row.title),status:String(row.status),type:"quest"})),...(er.data??[]).map(row=>({id:String(row.id),name:String(row.name),status:String(row.status),type:"enemy"})),...(mr.data??[]).map(row=>({id:String(row.id),name:String(row.name),status:String(row.status),type:"merchant"})),...(rr.data??[]).map(row=>({id:String(row.id),name:String(row.name),status:String(row.status),type:"recipe"})),...(fr.data??[]).map(row=>({id:String(row.id),name:String(row.name),status:String(row.status),type:"faction"})),...(cr.data??[]).map(row=>({id:String(row.id),name:String(row.name),status:String(row.status),type:"companion"}))]);setProfiles(pr.data??[]);setModeration(ur.data??[]);setAudit(ar.data??[]);}setLoading(false)},[supabase]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function setStatus(item:Content){const next=item.type==="quest"?(item.status==="available"?"disabled":"available"):(item.status==="published"?"draft":"published");setBusy(item.id);setError("");setMessage("");const{error:rpcError}=await supabase.rpc("admin_set_content_status",{p_content_type:item.type,p_record_id:item.id,p_status:next});if(rpcError)setError(adminError(rpcError.message));else{setMessage(`${item.name}: Status auf ${next} gesetzt.`);await load();}setBusy("");}
 async function setUserStatus(userId:string,status:string){const reason=status==="active"?null:window.prompt("Grund für die Moderation:")?.trim()||null;if(status!=="active"&&!reason)return;setBusy(userId);setError("");const{error:rpcError}=await supabase.rpc("admin_set_user_status",{p_user_id:userId,p_status:status,p_reason:reason});if(rpcError)setError(adminError(rpcError.message));else{setMessage("Benutzerstatus aktualisiert.");await load();}setBusy("");}
 async function setRole(userId:string,role:string){setBusy(`role-${userId}`);setError("");const{error:rpcError}=await supabase.rpc("admin_set_role",{p_user_id:userId,p_role:role});if(rpcError)setError(adminError(rpcError.message));else{setMessage("Adminrolle aktualisiert.");await load();}setBusy("");}
 if(loading)return <main className="mythoria-page flex min-h-screen items-center justify-center"><MythoriaSpinner size="large"/></main>;if(!overview)return <main className="mythoria-page mx-auto max-w-3xl px-4 py-12"><MythoriaAlert variant="error" title="Zugriff verweigert">{error||"Dieses Konto besitzt keine Adminrolle."}</MythoriaAlert></main>;const moderationMap=new Map(moderation.map(entry=>[entry.user_id,entry]));const canContent=overview.role!=="moderator";const canModerate=overview.role!=="content_admin";
 return <main className="mythoria-page mx-auto max-w-[1440px] px-4 py-8 sm:px-6"><MythoriaPageHeader eyebrow="ADMINISTRATION" title="Systemverwaltung" description="Geschützter Überblick über Inhalte, Benutzerstatus und sicherheitsrelevante Änderungen." actions={<MythoriaBadge variant="gold">{roleLabel(overview.role)}</MythoriaBadge>}/>{error&&<MythoriaAlert variant="error" className="mt-6">{error}</MythoriaAlert>}{message&&<MythoriaAlert variant="success" className="mt-6">{message}</MythoriaAlert>}
 <section className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries({Benutzer:overview.users,Charaktere:overview.characters,"Aktive Abenteuer":overview.activeAdventures,"Aktive Kämpfe":overview.activeCombats,Gilden:overview.guilds,Freundschaften:overview.friendships,Meldungen:overview.notifications,"Moderierte Konten":overview.suspendedUsers}).map(([label,value])=><article key={label} className="mythoria-card p-5"><p className="text-xs text-[var(--mythoria-text-muted)]">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</section>
 <section className="mt-12 border-t border-[var(--mythoria-border)] pt-10"><h2 className="mythoria-heading text-2xl">Inhaltsverwaltung</h2><div className="mythoria-panel mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-[var(--mythoria-border)] text-[var(--mythoria-gold-light)]"><tr><th className="p-4">Typ</th><th className="p-4">Name</th><th className="p-4">Status</th><th className="p-4">Aktion</th></tr></thead><tbody>{content.map(item=><tr key={`${item.type}-${item.id}`} className="border-b border-[var(--mythoria-border)]/50"><td className="p-4">{typeLabel(item.type)}</td><td className="p-4 font-bold">{item.name}</td><td className="p-4"><MythoriaBadge variant={item.status==="published"||item.status==="available"?"success":"neutral"}>{item.status}</MythoriaBadge></td><td className="p-4"><button disabled={!canContent||busy!==""} onClick={()=>void setStatus(item)} className="mythoria-button-secondary">{item.status==="published"||item.status==="available"?"Deaktivieren":"Veröffentlichen"}</button></td></tr>)}</tbody></table></div></section>
 <section className="mt-12 border-t border-[var(--mythoria-border)] pt-10"><h2 className="mythoria-heading text-2xl">Benutzerstatus</h2><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{profiles.map(profile=>{const state=moderationMap.get(profile.id)?.status??"active";return <article key={profile.id} className="mythoria-card p-4"><div className="flex items-center justify-between gap-3"><p className="font-bold">{profile.display_name}</p><MythoriaBadge variant={state==="active"?"success":state==="suspended"?"warning":"danger"}>{state}</MythoriaBadge></div>{canModerate&&<div className="mt-4 flex flex-wrap gap-2"><button disabled={busy!==""} onClick={()=>void setUserStatus(profile.id,"active")} className="mythoria-button-secondary">Aktiv</button><button disabled={busy!==""} onClick={()=>void setUserStatus(profile.id,"suspended")} className="mythoria-button-secondary">Sperren</button><button disabled={busy!==""} onClick={()=>void setUserStatus(profile.id,"banned")} className="mythoria-button-secondary">Bannen</button></div>}{overview.role==="super_admin"&&<select disabled={busy!==""} defaultValue="" onChange={event=>{if(event.target.value)void setRole(profile.id,event.target.value)}} className="mythoria-select mt-3"><option value="">Adminrolle vergeben</option><option value="content_admin">Inhaltsadmin</option><option value="moderator">Moderator</option><option value="super_admin">Super-Admin</option></select>}</article>})}</div></section>
 <section className="mt-12 border-t border-[var(--mythoria-border)] pt-10"><h2 className="mythoria-heading text-2xl">Auditprotokoll</h2><div className="mythoria-panel mt-5 divide-y divide-[var(--mythoria-border)]">{audit.length===0?<p className="p-5 text-sm text-[var(--mythoria-text-muted)]">Noch keine Adminaktionen protokolliert.</p>:audit.map(entry=><div key={entry.id} className="flex flex-col gap-1 p-4 text-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{entry.action}</p><p className="text-xs text-[var(--mythoria-text-muted)]">{entry.target_type} · {entry.target_id??"–"}</p></div><time className="text-xs text-[var(--mythoria-text-disabled)]">{new Date(entry.created_at).toLocaleString("de-DE")}</time></div>)}</div></section></main>}
function roleLabel(role:Overview["role"]){return{super_admin:"Super-Admin",content_admin:"Inhaltsadmin",moderator:"Moderator"}[role]}
function typeLabel(type:string){return{quest:"Quest",enemy:"Gegner",merchant:"Händler",recipe:"Rezept",faction:"Fraktion",companion:"Begleiter"}[type]??type}
function adminError(message:string){if(message.includes("admin access required"))return"Dieses Konto besitzt keine Adminberechtigung.";if(message.includes("content admin"))return"Für diese Aktion ist eine Inhaltsadmin-Rolle erforderlich.";if(message.includes("moderator"))return"Für diese Aktion ist eine Moderatorrolle erforderlich.";if(message.includes("cannot moderate own"))return"Das eigene Adminkonto kann nicht gesperrt werden.";return message}
