"use client";
import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { AuthShell } from "@/components/layout/AuthShell";
import { MythoriaAlert } from "@/components/ui/MythoriaAlert";

export default function LoginPage() {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(""); const router=useRouter(); const supabase=useMemo(()=>createClient(),[]);
  async function submit(event:FormEvent){event.preventDefault();setLoading(true);setMessage("");const{error}=await supabase.auth.signInWithPassword({email,password});if(error){setMessage(error.message==="Invalid login credentials"?"E-Mail oder Passwort ist falsch.":error.message);setLoading(false);return}router.replace("/dashboard");router.refresh()}
  async function social(provider:"google"|"discord"){setLoading(true);setMessage("");const{error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:`${window.location.origin}/dashboard`}});if(error){setMessage(error.message);setLoading(false)}}
  return <AuthShell title="Willkommen zurück" description="Melde dich an, um deine Chronik fortzusetzen."><div className="grid gap-3"><button type="button" onClick={()=>void social("google")} disabled={loading} className="mythoria-button-secondary w-full">Mit Google fortfahren</button><button type="button" onClick={()=>void social("discord")} disabled={loading} className="mythoria-button-secondary w-full">Mit Discord fortfahren</button></div><div className="my-6 flex items-center gap-3 text-xs text-[var(--mythoria-text-disabled)]"><span className="h-px flex-1 bg-[var(--mythoria-border)]" />oder mit E-Mail<span className="h-px flex-1 bg-[var(--mythoria-border)]" /></div><form onSubmit={submit} className="space-y-5"><label htmlFor="login-email" className="block text-sm font-semibold text-[var(--mythoria-gold-light)]">E-Mail<input id="login-email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} className="mythoria-input mt-2" /></label><label htmlFor="login-password" className="block text-sm font-semibold text-[var(--mythoria-gold-light)]">Passwort<input id="login-password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} className="mythoria-input mt-2" /></label><div className="text-right"><Link href="/forgot-password" className="text-sm text-[var(--mythoria-green-bright)] hover:text-[var(--mythoria-neon-soft)]">Passwort vergessen?</Link></div>{message&&<MythoriaAlert variant="error">{message}</MythoriaAlert>}<button disabled={loading} className="mythoria-button-primary w-full">{loading?"Die Chroniken werden geöffnet …":"Einloggen"}</button></form><p className="mt-6 text-center text-sm text-[var(--mythoria-text-muted)]">Noch kein Konto? <Link href="/register" className="font-bold text-[var(--mythoria-gold-light)]">Jetzt registrieren</Link></p></AuthShell>;
}
