"use client";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {MythoriaAlert} from "@/components/ui/MythoriaAlert";
import {MythoriaBadge} from "@/components/ui/MythoriaBadge";
import {MythoriaPageHeader} from "@/components/ui/MythoriaPageHeader";
import {MythoriaSpinner} from "@/components/ui/MythoriaSpinner";

type Character={id:string;name:string};type Faction={id:string;name:string;description:string;region:string;icon:string;color:string};type Reputation={faction_id:string;reputation:number};type Event={id:number;faction_id:string;amount:number;source_type:string;description:string;created_at:string};
const tiers=[{min:-1000,label:"Feindselig"},{min:-499,label:"Unfreundlich"},{min:-99,label:"Neutral"},{min:100,label:"Freundlich"},{min:300,label:"Geehrt"},{min:600,label:"Verehrt"}];
export default function ReputationPage(){const{id}=useParams<{id:string}>();const supabase=useMemo(()=>createClient(),[]);const[character,setCharacter]=useState<Character|null>(null);const[factions,setFactions]=useState<Faction[]>([]);const[reputations,setReputations]=useState<Reputation[]>([]);const[events,setEvents]=useState<Event[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Du bist nicht angemeldet.");setLoading(false);return;}const{data:c,error:ce}=await supabase.from("characters").select("id,name").eq("id",id).eq("user_id",user.id).maybeSingle().overrideTypes<Character|null,{merge:false}>();if(ce||!c){setError(ce?.message??"Charakter nicht gefunden.");setLoading(false);return;}setCharacter(c);const[fr,rr,er]=await Promise.all([supabase.from("factions").select("id,name,description,region,icon,color").order("sort_order").overrideTypes<Faction[],{merge:false}>(),supabase.from("character_reputation").select("faction_id,reputation").eq("character_id",id).eq("user_id",user.id).overrideTypes<Reputation[],{merge:false}>(),supabase.from("reputation_events").select("id,faction_id,amount,source_type,description,created_at").eq("character_id",id).eq("user_id",user.id).order("created_at",{ascending:false}).limit(20).overrideTypes<Event[],{merge:false}>()]);const first=fr.error??rr.error??er.error;if(first)setError(first.message);else{setFactions(fr.data??[]);setReputations(rr.data??[]);setEvents(er.data??[]);}setLoading(false)},[id,supabase]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);if(loading)return <main className="mythoria-page flex min-h-screen items-center justify-center"><MythoriaSpinner size="large"/></main>;if(!character)return <main className="mythoria-page mx-auto max-w-4xl px-4 py-10"><MythoriaAlert variant="error">{error||"Charakter nicht gefunden."}</MythoriaAlert></main>;
 const values=new Map(reputations.map(entry=>[entry.faction_id,entry.reputation]));const names=new Map(factions.map(faction=>[faction.id,faction.name]));
 return <main className="mythoria-page mx-auto max-w-6xl px-4 py-8 sm:px-6"><MythoriaPageHeader eyebrow="FRAKTIONEN & RUF" title={`Die Beziehungen von ${character.name}`} description="Quests und Siege verändern deinen Ruf. Positive Beziehungen gewähren bis zu 10 % zusätzlichen Händlerrabatt." actions={<Link href={`/dashboard/characters/${id}`} className="mythoria-button-secondary">Zum Charakter</Link>}/>{error&&<MythoriaAlert variant="error" className="mt-6">{error}</MythoriaAlert>}
 <section className="mt-8 grid gap-5 lg:grid-cols-3">{factions.map(faction=>{const value=values.get(faction.id)??0;const tier=tierFor(value);const percent=Math.min(100,Math.max(0,(value+1000)/20));return <article key={faction.id} className="mythoria-card p-6" style={{borderColor:`${faction.color}70`}}><div className="flex items-center justify-between gap-3"><span aria-hidden="true" className="text-4xl" style={{color:faction.color}}>{faction.icon}</span><MythoriaBadge variant={value>=300?"gold":value>=100?"success":value<=-100?"danger":"neutral"}>{tier}</MythoriaBadge></div><h2 className="mythoria-subheading mt-5 text-2xl">{faction.name}</h2><p className="mt-1 text-xs font-bold tracking-wide text-[var(--mythoria-gold-light)]">{faction.region}</p><p className="mt-4 min-h-24 text-sm leading-6 text-[var(--mythoria-text-muted)]">{faction.description}</p><div className="mt-5 flex items-center justify-between text-xs"><span>Ruf</span><strong>{value>0?"+":""}{value}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-black/35"><div className="h-full rounded-full" style={{width:`${percent}%`,background:faction.color}}/></div><p className="mt-3 text-xs text-[var(--mythoria-text-muted)]">Händlerrabatt: {Math.min(10,Math.max(0,value)/50).toFixed(1)} %</p></article>})}</section>
 <section className="mt-12 border-t border-[var(--mythoria-border)] pt-10"><h2 className="mythoria-heading text-2xl">Rufchronik</h2>{events.length===0?<p className="mt-4 text-sm text-[var(--mythoria-text-muted)]">Noch keine Taten haben deinen Ruf verändert.</p>:<div className="mythoria-panel mt-5 divide-y divide-[var(--mythoria-border)]">{events.map(event=><div key={event.id} className="flex items-center justify-between gap-4 p-4"><div><p className="font-bold">{event.description}</p><p className="mt-1 text-xs text-[var(--mythoria-text-muted)]">{names.get(event.faction_id)??"Fraktion"} · {new Date(event.created_at).toLocaleString("de-DE")}</p></div><strong className={event.amount>=0?"text-[var(--mythoria-success)]":"text-red-300"}>{event.amount>0?"+":""}{event.amount}</strong></div>)}</div>}</section></main>}
function tierFor(value:number){let result=tiers[0].label;for(const tier of tiers)if(value>=tier.min)result=tier.label;return result}
