"use client";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {MythoriaAlert} from "@/components/ui/MythoriaAlert";
import {MythoriaBadge} from "@/components/ui/MythoriaBadge";
import {MythoriaEmptyState} from "@/components/ui/MythoriaEmptyState";
import {MythoriaPageHeader} from "@/components/ui/MythoriaPageHeader";
import {MythoriaSpinner} from "@/components/ui/MythoriaSpinner";

type Character={id:string;name:string;level:number;gold:number};type Template={id:string;name:string;description:string;companion_class:string;role:string;required_level:number;recruitment_cost:number;required_faction_id:string|null;required_reputation:number;attack_bonus:number;defense_bonus:number;magic_bonus:number;icon:string};type Owned={id:string;companion_id:string;loyalty:number;party_slot:number|null};type Reputation={faction_id:string;reputation:number};type Faction={id:string;name:string};
export default function CompanionsPage(){const{id}=useParams<{id:string}>();const supabase=useMemo(()=>createClient(),[]);const[character,setCharacter]=useState<Character|null>(null);const[templates,setTemplates]=useState<Template[]>([]);const[owned,setOwned]=useState<Owned[]>([]);const[reputations,setReputations]=useState<Reputation[]>([]);const[factions,setFactions]=useState<Faction[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const{data:{user}}=await supabase.auth.getUser();if(!user){setError("Du bist nicht angemeldet.");setLoading(false);return;}const{data:c,error:ce}=await supabase.from("characters").select("id,name,level,gold").eq("id",id).eq("user_id",user.id).maybeSingle().overrideTypes<Character|null,{merge:false}>();if(ce||!c){setError(ce?.message??"Charakter nicht gefunden.");setLoading(false);return;}setCharacter(c);const[tr,or,rr,fr]=await Promise.all([supabase.from("companion_templates").select("id,name,description,companion_class,role,required_level,recruitment_cost,required_faction_id,required_reputation,attack_bonus,defense_bonus,magic_bonus,icon").order("sort_order").overrideTypes<Template[],{merge:false}>(),supabase.from("character_companions").select("id,companion_id,loyalty,party_slot").eq("character_id",id).eq("user_id",user.id).order("recruited_at").overrideTypes<Owned[],{merge:false}>(),supabase.from("character_reputation").select("faction_id,reputation").eq("character_id",id).eq("user_id",user.id).overrideTypes<Reputation[],{merge:false}>(),supabase.from("factions").select("id,name").overrideTypes<Faction[],{merge:false}>()]);const first=tr.error??or.error??rr.error??fr.error;if(first)setError(first.message);else{setTemplates(tr.data??[]);setOwned(or.data??[]);setReputations(rr.data??[]);setFactions(fr.data??[]);}setLoading(false)},[id,supabase]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function recruit(template:Template){setBusy(template.id);setError("");setMessage("");const{error:rpcError}=await supabase.rpc("recruit_companion",{p_character_id:id,p_companion_id:template.id});if(rpcError)setError(companionError(rpcError.message));else{setMessage(`${template.name} wurde rekrutiert.`);await load();}setBusy("");}
 async function toggle(entry:Owned,active:boolean){setBusy(entry.id);setError("");const{error:rpcError}=await supabase.rpc("set_companion_party_status",{p_character_companion_id:entry.id,p_active:active});if(rpcError)setError(companionError(rpcError.message));else await load();setBusy("");}
 async function dismiss(entry:Owned,name:string){if(!window.confirm(`${name} wirklich aus deiner Gefolgschaft entlassen?`))return;setBusy(entry.id);setError("");const{error:rpcError}=await supabase.rpc("dismiss_companion",{p_character_companion_id:entry.id});if(rpcError)setError(companionError(rpcError.message));else{setMessage(`${name} wurde entlassen.`);await load();}setBusy("");}
 if(loading)return <main className="mythoria-page flex min-h-screen items-center justify-center"><MythoriaSpinner size="large"/></main>;if(!character)return <main className="mythoria-page mx-auto max-w-4xl px-4 py-10"><MythoriaAlert variant="error">{error||"Charakter nicht gefunden."}</MythoriaAlert></main>;
 const ownedByTemplate=new Map(owned.map(entry=>[entry.companion_id,entry]));const reputation=new Map(reputations.map(entry=>[entry.faction_id,entry.reputation]));const factionNames=new Map(factions.map(entry=>[entry.id,entry.name]));const active=owned.filter(entry=>entry.party_slot!==null).sort((a,b)=>(a.party_slot??0)-(b.party_slot??0));
 return <main className="mythoria-page mx-auto max-w-6xl px-4 py-8 sm:px-6"><MythoriaPageHeader eyebrow="BEGLEITER & GRUPPE" title={`Die Gefolgschaft von ${character.name}`} description="Rekrutiere Verbündete und stelle eine aktive Gruppe aus höchstens zwei Begleitern zusammen." actions={<div className="flex flex-wrap gap-3"><MythoriaBadge variant="gold">{character.gold} Gold</MythoriaBadge><Link href={`/dashboard/characters/${id}`} className="mythoria-button-secondary">Zum Charakter</Link></div>}/>{error&&<MythoriaAlert variant="error" className="mt-6">{error}</MythoriaAlert>}{message&&<MythoriaAlert variant="success" className="mt-6">{message}</MythoriaAlert>}
 <section className="mt-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[.18em] text-[var(--mythoria-green-bright)]">AKTIVE GRUPPE</p><h2 className="mythoria-heading mt-1 text-2xl">Gemeinsam unterwegs</h2></div><MythoriaBadge variant={active.length===2?"gold":"neutral"}>{active.length}/2 Plätze</MythoriaBadge></div>{active.length===0?<MythoriaEmptyState className="mt-5" title="Noch allein unterwegs" description="Aktiviere einen rekrutierten Begleiter für deine Gruppe."/>:<div className="mt-5 grid gap-4 md:grid-cols-2">{active.map(entry=>{const template=templates.find(item=>item.id===entry.companion_id);if(!template)return null;return <CompanionCard key={entry.id} template={template} entry={entry} busy={busy} action={<button disabled={busy!==""} onClick={()=>void toggle(entry,false)} className="mythoria-button-secondary w-full">Aus Gruppe nehmen</button>}/>})}</div>}</section>
 <section className="mt-12 border-t border-[var(--mythoria-border)] pt-10"><h2 className="mythoria-heading text-2xl">Verfügbare Gefährten</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{templates.map(template=>{const entry=ownedByTemplate.get(template.id);const requiredRep=template.required_faction_id?reputation.get(template.required_faction_id)??0:0;const eligible=character.level>=template.required_level&&character.gold>=template.recruitment_cost&&requiredRep>=template.required_reputation;return <CompanionCard key={template.id} template={template} entry={entry} busy={busy} requirement={template.required_faction_id?`${factionNames.get(template.required_faction_id)??"Fraktion"}: ${requiredRep}/${template.required_reputation} Ruf`:undefined} action={entry?<div className="grid grid-cols-2 gap-2"><button disabled={busy!==""||entry.party_slot!==null||active.length>=2} onClick={()=>void toggle(entry,true)} className="mythoria-button-primary">In Gruppe</button><button disabled={busy!==""} onClick={()=>void dismiss(entry,template.name)} className="mythoria-button-secondary">Entlassen</button></div>:<button disabled={busy!==""||!eligible} onClick={()=>void recruit(template)} className="mythoria-button-primary w-full">{character.level<template.required_level?`Ab Stufe ${template.required_level}`:requiredRep<template.required_reputation?"Ruf nicht ausreichend":`${template.recruitment_cost} Gold · Rekrutieren`}</button>}/>})}</div></section></main>}
function CompanionCard({template,entry,busy,requirement,action}:{template:Template;entry?:Owned;busy:string;requirement?:string;action:React.ReactNode}){return <article className={`mythoria-card p-5 ${entry?.party_slot!==null&&entry?"border-[var(--mythoria-success)]":""}`}><div className="flex items-start justify-between gap-3"><span aria-hidden="true" className="flex h-14 w-14 items-center justify-center rounded-xl border border-[var(--mythoria-border-gold)] bg-black/20 text-3xl">{template.icon}</span><MythoriaBadge variant={entry?"success":"neutral"}>{entry?entry.party_slot?`Gruppe · Platz ${entry.party_slot}`:"Rekrutiert":roleLabel(template.role)}</MythoriaBadge></div><h3 className="mythoria-subheading mt-4 text-xl">{template.name}</h3><p className="mt-1 text-xs font-bold text-[var(--mythoria-gold-light)]">{template.companion_class} · {roleLabel(template.role)}</p><p className="mt-3 min-h-20 text-sm leading-6 text-[var(--mythoria-text-muted)]">{template.description}</p><div className="mt-4 flex flex-wrap gap-2 text-xs"><span>+{template.attack_bonus} Angriff</span><span>+{template.defense_bonus} Verteidigung</span><span>+{template.magic_bonus} Magie</span></div>{entry&&<div className="mt-4"><div className="flex justify-between text-xs"><span>Loyalität</span><span>{entry.loyalty}/100</span></div><div className="mt-2 h-2 rounded-full bg-black/30"><div className="h-full rounded-full bg-[var(--mythoria-success)]" style={{width:`${entry.loyalty}%`}}/></div></div>}{requirement&&<p className="mt-3 text-xs text-[var(--mythoria-text-muted)]">Voraussetzung: {requirement}</p>}<div className="mt-5" aria-busy={busy!==""}>{action}</div></article>}
function roleLabel(role:string){return{damage:"Angriff",tank:"Schutz",support:"Unterstützung",healer:"Heilung"}[role]??role}
function companionError(message:string){if(message.includes("party is full"))return"Die aktive Gruppe besitzt bereits zwei Begleiter.";if(message.includes("not enough gold"))return"Für die Rekrutierung ist nicht genug Gold vorhanden.";if(message.includes("level too low"))return"Die benötigte Charakterstufe wurde noch nicht erreicht.";if(message.includes("reputation too low"))return"Der benötigte Fraktionsruf wurde noch nicht erreicht.";if(message.includes("already recruited"))return"Dieser Begleiter gehört bereits zur Gefolgschaft.";return message}
