begin;
create table if not exists public.notifications(
 id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,
 notification_type text not null,title text not null,message text not null,link text,dedupe_key text,read_at timestamptz,created_at timestamptz not null default now(),
 constraint notifications_type_allowed check(notification_type in('friend','party','guild','achievement','system')),
 constraint notifications_title_length check(char_length(title) between 2 and 100),constraint notifications_message_length check(char_length(message) between 2 and 400),
 unique(user_id,dedupe_key)
);create index if not exists notifications_user_created_idx on public.notifications(user_id,created_at desc);create index if not exists notifications_user_unread_idx on public.notifications(user_id) where read_at is null;
alter table public.notifications enable row level security;create policy "notifications_own_read" on public.notifications for select to authenticated using((select auth.uid())=user_id);
revoke all on public.notifications from anon;revoke insert,update,delete on public.notifications from authenticated;grant select on public.notifications to authenticated;

create or replace function public.create_notification(p_user uuid,p_type text,p_title text,p_message text,p_link text,p_key text)
returns void language plpgsql security definer set search_path=public as $$begin insert into public.notifications(user_id,notification_type,title,message,link,dedupe_key) values(p_user,p_type,left(p_title,100),left(p_message,400),p_link,p_key) on conflict(user_id,dedupe_key) do update set title=excluded.title,message=excluded.message,link=excluded.link,read_at=null,created_at=now();end;$$;
create or replace function public.friendship_notifications() returns trigger language plpgsql security definer set search_path=public as $$declare v_name text;begin select display_name into v_name from public.public_profiles where id=new.requester_id;if tg_op='INSERT' and new.status='pending' then perform public.create_notification(new.addressee_id,'friend','Neue Freundschaftsanfrage',v_name||' möchte dich als Freund hinzufügen.','/dashboard/social','friend-request-'||new.id);elsif tg_op='UPDATE' and new.status='accepted' and old.status is distinct from 'accepted' then select display_name into v_name from public.public_profiles where id=new.addressee_id;perform public.create_notification(new.requester_id,'friend','Freundschaft bestätigt',v_name||' hat deine Freundschaftsanfrage angenommen.','/dashboard/social','friend-accepted-'||new.id);end if;return new;end;$$;
drop trigger if exists friendships_create_notifications on public.friendships;create trigger friendships_create_notifications after insert or update of status on public.friendships for each row execute function public.friendship_notifications();

create or replace function public.party_invite_notifications() returns trigger language plpgsql security definer set search_path=public as $$declare v_name text;v_party text;begin if new.status='pending' then select display_name into v_name from public.public_profiles where id=new.inviter_id;select name into v_party from public.multiplayer_parties where id=new.party_id;perform public.create_notification(new.invitee_id,'party','Einladung zur Abenteuergruppe',v_name||' lädt dich in „'||v_party||'“ ein.','/dashboard/social','party-invite-'||new.id);end if;return new;end;$$;
drop trigger if exists party_invites_create_notifications on public.multiplayer_party_invites;create trigger party_invites_create_notifications after insert or update of status on public.multiplayer_party_invites for each row execute function public.party_invite_notifications();

create or replace function public.guild_member_notifications() returns trigger language plpgsql security definer set search_path=public as $$declare v_guild text;begin select name into v_guild from public.guilds where id=new.guild_id;perform public.create_notification(new.user_id,'guild','Gildenmitgliedschaft','Du gehörst jetzt zur Gilde „'||v_guild||'“.','/dashboard/social','guild-member-'||new.id);return new;end;$$;
drop trigger if exists guild_members_create_notifications on public.guild_members;create trigger guild_members_create_notifications after insert on public.guild_members for each row execute function public.guild_member_notifications();

create or replace function public.achievement_notifications() returns trigger language plpgsql security definer set search_path=public as $$declare v_title text;v_description text;begin select title,description into v_title,v_description from public.achievements where id=new.achievement_id;perform public.create_notification(new.user_id,'achievement','Erfolg freigeschaltet: '||v_title,v_description,'/dashboard/achievements','achievement-'||new.id);return new;end;$$;
drop trigger if exists character_achievements_create_notifications on public.character_achievements;create trigger character_achievements_create_notifications after insert on public.character_achievements for each row execute function public.achievement_notifications();

create or replace function public.mark_notification_read(p_notification_id uuid) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();begin update public.notifications set read_at=coalesce(read_at,now()) where id=p_notification_id and user_id=v_user;if not found then raise exception 'notification not found';end if;end;$$;
create or replace function public.mark_all_notifications_read() returns void language sql security definer set search_path=public as $$update public.notifications set read_at=coalesce(read_at,now()) where user_id=auth.uid() and read_at is null$$;
create or replace function public.delete_notification(p_notification_id uuid) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();begin delete from public.notifications where id=p_notification_id and user_id=v_user;if not found then raise exception 'notification not found';end if;end;$$;
revoke all on function public.create_notification(uuid,text,text,text,text,text),public.friendship_notifications(),public.party_invite_notifications(),public.guild_member_notifications(),public.achievement_notifications() from public,anon,authenticated;
revoke all on function public.mark_notification_read(uuid),public.mark_all_notifications_read(),public.delete_notification(uuid) from public,anon;
grant execute on function public.mark_notification_read(uuid),public.mark_all_notifications_read(),public.delete_notification(uuid) to authenticated;
notify pgrst,'reload schema';commit;
