begin;
create table if not exists public.public_profiles(
 id uuid primary key references auth.users(id) on delete cascade,display_name text not null default 'Abenteurer',avatar_url text,
 friend_code text not null unique default upper(substr(replace(gen_random_uuid()::text,'-',''),1,8)),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 constraint public_profiles_name_length check(char_length(display_name) between 2 and 60),constraint public_profiles_code_format check(friend_code~'^[A-Z0-9]{8}$')
);
create trigger public_profiles_set_updated_at before update on public.public_profiles for each row execute function public.set_updated_at();
create or replace function public.create_public_profile() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.public_profiles(id,display_name,avatar_url) values(new.id,coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'),''),split_part(coalesce(new.email,'Abenteurer'),'@',1)),nullif(new.raw_user_meta_data->>'avatar_url','')) on conflict(id) do nothing;return new;end;$$;
drop trigger if exists auth_user_create_public_profile on auth.users;create trigger auth_user_create_public_profile after insert on auth.users for each row execute function public.create_public_profile();
insert into public.public_profiles(id,display_name,avatar_url) select id,coalesce(nullif(trim(raw_user_meta_data->>'display_name'),''),split_part(coalesce(email,'Abenteurer'),'@',1)),nullif(raw_user_meta_data->>'avatar_url','') from auth.users on conflict(id) do nothing;

create table if not exists public.friendships(
 id uuid primary key default gen_random_uuid(),requester_id uuid not null references auth.users(id) on delete cascade,addressee_id uuid not null references auth.users(id) on delete cascade,
 status text not null default 'pending',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 constraint friendships_not_self check(requester_id<>addressee_id),constraint friendships_status_allowed check(status in('pending','accepted','blocked')),unique(requester_id,addressee_id)
);create trigger friendships_set_updated_at before update on public.friendships for each row execute function public.set_updated_at();

create table if not exists public.guilds(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete restrict,name text not null unique,description text not null default '',join_code text not null unique default upper(substr(replace(gen_random_uuid()::text,'-',''),1,8)),created_at timestamptz not null default now(),constraint guild_name_length check(char_length(name) between 3 and 50));
create table if not exists public.guild_members(id uuid primary key default gen_random_uuid(),guild_id uuid not null references public.guilds(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null default 'member',joined_at timestamptz not null default now(),unique(user_id),constraint guild_role_allowed check(role in('owner','officer','member')));

create table if not exists public.multiplayer_parties(id uuid primary key default gen_random_uuid(),leader_id uuid not null references auth.users(id) on delete cascade,name text not null,status text not null default 'forming',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint multiplayer_party_status_allowed check(status in('forming','ready','completed')));create trigger multiplayer_parties_set_updated_at before update on public.multiplayer_parties for each row execute function public.set_updated_at();
create table if not exists public.multiplayer_party_members(id uuid primary key default gen_random_uuid(),party_id uuid not null references public.multiplayer_parties(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,character_id uuid not null references public.characters(id) on delete cascade,is_ready boolean not null default false,joined_at timestamptz not null default now(),unique(party_id,user_id),unique(party_id,character_id));
create table if not exists public.multiplayer_party_invites(id uuid primary key default gen_random_uuid(),party_id uuid not null references public.multiplayer_parties(id) on delete cascade,inviter_id uuid not null references auth.users(id) on delete cascade,invitee_id uuid not null references auth.users(id) on delete cascade,status text not null default 'pending',created_at timestamptz not null default now(),unique(party_id,invitee_id),constraint party_invite_status_allowed check(status in('pending','accepted','declined')));

alter table public.public_profiles enable row level security;alter table public.friendships enable row level security;alter table public.guilds enable row level security;alter table public.guild_members enable row level security;alter table public.multiplayer_parties enable row level security;alter table public.multiplayer_party_members enable row level security;alter table public.multiplayer_party_invites enable row level security;
create policy "profiles_authenticated_read" on public.public_profiles for select to authenticated using(true);create policy "profiles_update_own" on public.public_profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);
create policy "friendships_own_read" on public.friendships for select to authenticated using((select auth.uid()) in(requester_id,addressee_id));
create or replace function public.is_guild_member(p_guild uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.guild_members where guild_id=p_guild and user_id=auth.uid())$$;
create or replace function public.is_party_member(p_party uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.multiplayer_party_members where party_id=p_party and user_id=auth.uid())$$;
create policy "guilds_member_read" on public.guilds for select to authenticated using(public.is_guild_member(id));create policy "guild_members_member_read" on public.guild_members for select to authenticated using(public.is_guild_member(guild_id));
create policy "parties_member_read" on public.multiplayer_parties for select to authenticated using(public.is_party_member(id));create policy "party_members_member_read" on public.multiplayer_party_members for select to authenticated using(public.is_party_member(party_id));create policy "party_invites_own_read" on public.multiplayer_party_invites for select to authenticated using((select auth.uid()) in(inviter_id,invitee_id));
revoke all on public.public_profiles,public.friendships,public.guilds,public.guild_members,public.multiplayer_parties,public.multiplayer_party_members,public.multiplayer_party_invites from anon;
revoke insert,update,delete on public.friendships,public.guilds,public.guild_members,public.multiplayer_parties,public.multiplayer_party_members,public.multiplayer_party_invites from authenticated;
grant select on public.friendships,public.guilds,public.guild_members,public.multiplayer_parties,public.multiplayer_party_members,public.multiplayer_party_invites to authenticated;
grant select(id,display_name,avatar_url,created_at) on public.public_profiles to authenticated;grant update(display_name,avatar_url) on public.public_profiles to authenticated;

create or replace function public.get_my_friend_code() returns text language sql stable security definer set search_path=public as $$select friend_code from public.public_profiles where id=auth.uid()$$;

create or replace function public.send_friend_request(p_friend_code text) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_target uuid;begin if v_user is null then raise exception 'authentication required';end if;select id into v_target from public.public_profiles where friend_code=upper(trim(p_friend_code));if v_target is null then raise exception 'profile not found';end if;if v_target=v_user then raise exception 'cannot friend yourself';end if;if exists(select 1 from public.friendships where (requester_id=v_user and addressee_id=v_target) or(requester_id=v_target and addressee_id=v_user)) then raise exception 'friendship already exists';end if;insert into public.friendships(requester_id,addressee_id) values(v_user,v_target);end;$$;
create or replace function public.respond_friend_request(p_friendship_id uuid,p_accept boolean) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();begin if p_accept then update public.friendships set status='accepted' where id=p_friendship_id and addressee_id=v_user and status='pending';else delete from public.friendships where id=p_friendship_id and addressee_id=v_user and status='pending';end if;if not found then raise exception 'pending request not found';end if;end;$$;
create or replace function public.remove_friendship(p_friendship_id uuid) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();begin delete from public.friendships where id=p_friendship_id and v_user in(requester_id,addressee_id);if not found then raise exception 'friendship not found';end if;end;$$;

create or replace function public.create_guild(p_name text,p_description text default '') returns uuid language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_id uuid;begin if v_user is null then raise exception 'authentication required';end if;if char_length(trim(p_name)) not between 3 and 50 then raise exception 'invalid guild name';end if;if exists(select 1 from public.guild_members where user_id=v_user) then raise exception 'already in guild';end if;insert into public.guilds(owner_id,name,description) values(v_user,trim(p_name),left(trim(p_description),500)) returning id into v_id;insert into public.guild_members(guild_id,user_id,role) values(v_id,v_user,'owner');return v_id;end;$$;
create or replace function public.join_guild(p_join_code text) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_guild uuid;begin if exists(select 1 from public.guild_members where user_id=v_user) then raise exception 'already in guild';end if;select id into v_guild from public.guilds where join_code=upper(trim(p_join_code));if v_guild is null then raise exception 'guild not found';end if;insert into public.guild_members(guild_id,user_id) values(v_guild,v_user);end;$$;
create or replace function public.leave_guild() returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_member record;begin select * into v_member from public.guild_members where user_id=v_user;if v_member.id is null then raise exception 'not in guild';end if;if v_member.role='owner' and exists(select 1 from public.guild_members where guild_id=v_member.guild_id and user_id<>v_user) then raise exception 'owner must transfer guild';end if;if v_member.role='owner' then delete from public.guilds where id=v_member.guild_id;else delete from public.guild_members where id=v_member.id;end if;end;$$;

create or replace function public.create_multiplayer_party(p_character_id uuid,p_name text) returns uuid language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_party uuid;begin if not exists(select 1 from public.characters where id=p_character_id and user_id=v_user) then raise exception 'character not found';end if;if exists(select 1 from public.multiplayer_party_members pm join public.multiplayer_parties p on p.id=pm.party_id where pm.user_id=v_user and p.status in('forming','ready')) then raise exception 'already in party';end if;insert into public.multiplayer_parties(leader_id,name) values(v_user,left(coalesce(nullif(trim(p_name),''),'Abenteuergruppe'),60)) returning id into v_party;insert into public.multiplayer_party_members(party_id,user_id,character_id) values(v_party,v_user,p_character_id);return v_party;end;$$;
create or replace function public.invite_friend_to_party(p_party_id uuid,p_friend_id uuid) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();begin if not exists(select 1 from public.multiplayer_parties where id=p_party_id and leader_id=v_user and status='forming') then raise exception 'party unavailable';end if;if not exists(select 1 from public.friendships where status='accepted' and((requester_id=v_user and addressee_id=p_friend_id)or(requester_id=p_friend_id and addressee_id=v_user))) then raise exception 'user is not a friend';end if;insert into public.multiplayer_party_invites(party_id,inviter_id,invitee_id) values(p_party_id,v_user,p_friend_id) on conflict(party_id,invitee_id) do update set status='pending',created_at=now();end;$$;
create or replace function public.respond_party_invite(p_invite_id uuid,p_accept boolean,p_character_id uuid default null) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_invite record;begin select * into v_invite from public.multiplayer_party_invites where id=p_invite_id and invitee_id=v_user and status='pending' for update;if v_invite.id is null then raise exception 'invite not found';end if;if not p_accept then update public.multiplayer_party_invites set status='declined' where id=v_invite.id;return;end if;if not exists(select 1 from public.characters where id=p_character_id and user_id=v_user) then raise exception 'character not found';end if;if(select count(*) from public.multiplayer_party_members where party_id=v_invite.party_id)>=4 then raise exception 'party is full';end if;insert into public.multiplayer_party_members(party_id,user_id,character_id) values(v_invite.party_id,v_user,p_character_id);update public.multiplayer_party_invites set status='accepted' where id=v_invite.id;end;$$;
create or replace function public.set_party_ready(p_party_id uuid,p_ready boolean) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();begin update public.multiplayer_party_members set is_ready=p_ready where party_id=p_party_id and user_id=v_user;if not found then raise exception 'party membership not found';end if;update public.multiplayer_parties set status=case when not exists(select 1 from public.multiplayer_party_members where party_id=p_party_id and is_ready=false) and(select count(*) from public.multiplayer_party_members where party_id=p_party_id)>=2 then 'ready' else 'forming' end where id=p_party_id;end;$$;
create or replace function public.leave_multiplayer_party(p_party_id uuid) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_leader uuid;begin select leader_id into v_leader from public.multiplayer_parties where id=p_party_id;if v_leader=v_user then delete from public.multiplayer_parties where id=p_party_id;else delete from public.multiplayer_party_members where party_id=p_party_id and user_id=v_user;if not found then raise exception 'party membership not found';end if;end if;end;$$;

revoke all on function public.create_public_profile() from public,anon,authenticated;
revoke all on function public.is_guild_member(uuid),public.is_party_member(uuid) from public,anon;
grant execute on function public.is_guild_member(uuid),public.is_party_member(uuid) to authenticated;
revoke all on function public.get_my_friend_code(),public.send_friend_request(text),public.respond_friend_request(uuid,boolean),public.remove_friendship(uuid),public.create_guild(text,text),public.join_guild(text),public.leave_guild(),public.create_multiplayer_party(uuid,text),public.invite_friend_to_party(uuid,uuid),public.respond_party_invite(uuid,boolean,uuid),public.set_party_ready(uuid,boolean),public.leave_multiplayer_party(uuid) from public,anon;
grant execute on function public.get_my_friend_code(),public.send_friend_request(text),public.respond_friend_request(uuid,boolean),public.remove_friendship(uuid),public.create_guild(text,text),public.join_guild(text),public.leave_guild(),public.create_multiplayer_party(uuid,text),public.invite_friend_to_party(uuid,uuid),public.respond_party_invite(uuid,boolean,uuid),public.set_party_ready(uuid,boolean),public.leave_multiplayer_party(uuid) to authenticated;
notify pgrst,'reload schema';commit;
