begin;
create table if not exists public.admin_users(user_id uuid primary key references auth.users(id) on delete cascade,role text not null,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),constraint admin_role_allowed check(role in('super_admin','content_admin','moderator')));
create table if not exists public.user_moderation(user_id uuid primary key references auth.users(id) on delete cascade,status text not null default 'active',reason text,moderated_by uuid references auth.users(id) on delete set null,updated_at timestamptz not null default now(),constraint user_moderation_status_allowed check(status in('active','suspended','banned')));create trigger user_moderation_set_updated_at before update on public.user_moderation for each row execute function public.set_updated_at();
create table if not exists public.admin_audit_log(id bigint generated always as identity primary key,admin_id uuid not null references auth.users(id) on delete restrict,action text not null,target_type text not null,target_id text,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());create index if not exists admin_audit_created_idx on public.admin_audit_log(created_at desc);

create or replace function public.is_admin(p_roles text[] default null) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.admin_users where user_id=auth.uid() and(p_roles is null or role=any(p_roles)))$$;
alter table public.admin_users enable row level security;alter table public.user_moderation enable row level security;alter table public.admin_audit_log enable row level security;
create policy "admin_users_admin_read" on public.admin_users for select to authenticated using(public.is_admin());create policy "moderation_admin_read" on public.user_moderation for select to authenticated using(public.is_admin());create policy "moderation_own_read" on public.user_moderation for select to authenticated using((select auth.uid())=user_id);create policy "audit_admin_read" on public.admin_audit_log for select to authenticated using(public.is_admin());
revoke all on public.admin_users,public.user_moderation,public.admin_audit_log from anon;revoke insert,update,delete on public.admin_users,public.user_moderation,public.admin_audit_log from authenticated;grant select on public.admin_users,public.user_moderation,public.admin_audit_log to authenticated;
insert into public.admin_users(user_id,role) select id,'super_admin' from auth.users where (select count(*) from auth.users)=1 on conflict(user_id) do nothing;

create policy "quests_admin_read" on public.quests for select to authenticated using(public.is_admin(array['super_admin','content_admin']));
create policy "enemies_admin_read" on public.enemies for select to authenticated using(public.is_admin(array['super_admin','content_admin']));
create policy "merchants_admin_read" on public.merchants for select to authenticated using(public.is_admin(array['super_admin','content_admin']));
create policy "recipes_admin_read" on public.crafting_recipes for select to authenticated using(public.is_admin(array['super_admin','content_admin']));
create policy "factions_admin_read" on public.factions for select to authenticated using(public.is_admin(array['super_admin','content_admin']));
create policy "companions_admin_read" on public.companion_templates for select to authenticated using(public.is_admin(array['super_admin','content_admin']));

create or replace function public.get_admin_overview() returns jsonb language plpgsql stable security definer set search_path=public as $$declare v_user uuid:=auth.uid();begin if not public.is_admin() then raise exception 'admin access required';end if;return jsonb_build_object('users',(select count(*) from public.public_profiles),'characters',(select count(*) from public.characters),'activeAdventures',(select count(*) from public.adventure_sessions where status='active'),'activeCombats',(select count(*) from public.combat_sessions where status='active'),'guilds',(select count(*) from public.guilds),'friendships',(select count(*) from public.friendships where status='accepted'),'notifications',(select count(*) from public.notifications),'suspendedUsers',(select count(*) from public.user_moderation where status<>'active'),'role',(select role from public.admin_users where user_id=v_user));end;$$;
create or replace function public.admin_set_content_status(p_content_type text,p_record_id text,p_status text) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();v_table text;v_count integer;begin if not public.is_admin(array['super_admin','content_admin']) then raise exception 'content admin access required';end if;if p_status not in('published','draft','disabled','available') then raise exception 'invalid content status';end if;v_table:=case p_content_type when 'quest' then 'quests' when 'enemy' then 'enemies' when 'merchant' then 'merchants' when 'recipe' then 'crafting_recipes' when 'faction' then 'factions' when 'companion' then 'companion_templates' else null end;if v_table is null then raise exception 'invalid content type';end if;if v_table='quests' and p_status not in('available','disabled') then raise exception 'invalid quest status';elsif v_table<>'quests' and p_status not in('published','draft') then raise exception 'invalid content status';end if;execute format('update public.%I set status=$1 where id::text=$2',v_table) using p_status,p_record_id;get diagnostics v_count=row_count;if v_count<>1 then raise exception 'content not found';end if;insert into public.admin_audit_log(admin_id,action,target_type,target_id,details) values(v_user,'content_status_changed',p_content_type,p_record_id,jsonb_build_object('status',p_status));end;$$;
create or replace function public.admin_set_user_status(p_user_id uuid,p_status text,p_reason text default null) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();begin if not public.is_admin(array['super_admin','moderator']) then raise exception 'moderator access required';end if;if p_status not in('active','suspended','banned') then raise exception 'invalid user status';end if;if p_user_id=v_user and p_status<>'active' then raise exception 'cannot moderate own account';end if;if not exists(select 1 from public.public_profiles where id=p_user_id) then raise exception 'user not found';end if;insert into public.user_moderation(user_id,status,reason,moderated_by) values(p_user_id,p_status,nullif(left(trim(coalesce(p_reason,'')),500),''),v_user) on conflict(user_id) do update set status=excluded.status,reason=excluded.reason,moderated_by=excluded.moderated_by,updated_at=now();insert into public.admin_audit_log(admin_id,action,target_type,target_id,details) values(v_user,'user_status_changed','user',p_user_id::text,jsonb_build_object('status',p_status,'reason',p_reason));end;$$;
create or replace function public.admin_set_role(p_user_id uuid,p_role text) returns void language plpgsql security definer set search_path=public as $$declare v_user uuid:=auth.uid();begin if not public.is_admin(array['super_admin']) then raise exception 'super admin access required';end if;if p_role not in('super_admin','content_admin','moderator') then raise exception 'invalid admin role';end if;insert into public.admin_users(user_id,role,created_by) values(p_user_id,p_role,v_user) on conflict(user_id) do update set role=excluded.role;insert into public.admin_audit_log(admin_id,action,target_type,target_id,details) values(v_user,'admin_role_changed','user',p_user_id::text,jsonb_build_object('role',p_role));end;$$;
revoke all on function public.is_admin(text[]) from public,anon;grant execute on function public.is_admin(text[]) to authenticated;
revoke all on function public.get_admin_overview(),public.admin_set_content_status(text,text,text),public.admin_set_user_status(uuid,text,text),public.admin_set_role(uuid,text) from public,anon;
grant execute on function public.get_admin_overview(),public.admin_set_content_status(text,text,text),public.admin_set_user_status(uuid,text,text),public.admin_set_role(uuid,text) to authenticated;
notify pgrst,'reload schema';commit;
